services:
  mysql:
    image: mysql:8.0
    container_name: goosage-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: goosage_local
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - goosage_mysql_data:/var/lib/mysql

volumes:
  goosage_mysql_data: